# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fdc9337da182bf0be4f3f7f3243cfec95c3e00a6e9bc73ff83933030d68bf38c7ebdf96be16efc626911953eb49b107cf06809e54339b8ba66674bf1f7a50c7d

test:
  secret_key_base: 64c56c0a5aac27b95bc8717de1e9fd694f09ebceee16de10066bdbf4bdf3e7a047fd547bb570a1f302868d288ad065d125793e18bbda4afbc6ee93e167548017

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
